# Project: cat-game
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"S:/dev-c++/Dev-Cpp/MinGW64/lib" -L"S:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/SFML/lib" -lsfml-audio -lsfml-graphics -lsfml-system -lsfml-window
INCS     = -I"S:/dev-c++/Dev-Cpp/MinGW64/include" -I"S:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"S:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/SFML/include"
CXXINCS  = -I"S:/dev-c++/Dev-Cpp/MinGW64/include" -I"S:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"S:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"S:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/SFML/include"
BIN      = cat-game.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
